#!/usr/bin/env node
/**
 * Writes `lib/flags.ts` with one seamless, tileable flag strip per language.
 *
 * Same reasoning as `generate-tech-icons.mjs`: `country-flag-icons` ships every
 * country on earth, so the ones we want are extracted at build time and the
 * package stays a devDependency with no runtime presence.
 *
 * The output is a data URI per language rather than a list of markup, because
 * the band this feeds is permanent. Filling a wide header with a repeating row
 * of individual <svg> elements would take well over a hundred of them — several
 * hundred DOM nodes that exist purely to be 14% visible. One repeating
 * background image costs a single element, and lets the drift animate
 * `transform`, which the compositor can do without touching layout or paint.
 *
 * Usage: node scripts/generate-flags.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Countries per language.
 *
 * Not "every country where the language is spoken" — that list runs past fifty
 * and says nothing. These are the ones a reader recognises at a glance, capped
 * at eight so the strip stays a flourish.
 */
const BY_LOCALE = {
  // The CPLP, minus the members whose flags are unreadable at this size.
  pt: ["PT", "BR", "AO", "MZ", "CV", "GW", "ST", "TL"],
  en: ["GB", "US", "CA", "IE", "AU", "NZ", "ZA", "IN"],
  es: ["ES", "MX", "AR", "CO", "CL", "PE", "UY", "CU"],
};

/** Strip geometry, in the tile's own units. 3:2 flags, one gap between each. */
const FLAG_W = 24;
const FLAG_H = 16;
const GAP = 18;
const PITCH = FLAG_W + GAP;

const inner = (svg) => svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");

const read = (code) =>
  inner(readFileSync(resolve(ROOT, `node_modules/country-flag-icons/3x2/${code}.svg`), "utf8"));

/**
 * One tile: the eight flags in a row, with the trailing gap included so that
 * repeating the image butts the last flag against the first at exactly one
 * pitch. Anything else shows a seam.
 */
function strip(codes) {
  const width = codes.length * PITCH;
  const flags = codes
    .map(
      (code, i) =>
        `<svg x="${i * PITCH}" y="0" width="${FLAG_W}" height="${FLAG_H}" viewBox="0 0 513 342">${read(code)}</svg>`,
    )
    .join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${FLAG_H}" viewBox="0 0 ${width} ${FLAG_H}">${flags}</svg>`;
  return { width, uri: `data:image/svg+xml,${encodeURIComponent(svg)}` };
}

const strips = Object.fromEntries(
  Object.entries(BY_LOCALE).map(([locale, codes]) => [locale, strip(codes)]),
);

const file = `// Generated by scripts/generate-flags.mjs — do not edit by hand.
// Source: country-flag-icons (3x2).

import type { Locale } from "@/lib/i18n/types";

export type FlagStrip = {
  /** Data URI of one tile: the language's flags in a row, gap included. */
  uri: string;
  /** Tile width in the image's own units; its height is ${FLAG_H}. */
  width: number;
};

/**
 * A tileable strip per language. Repeat it along x and shift by exactly
 * \`width\` (scaled) for a seamless loop.
 */
export const flagStrips: Record<Locale, FlagStrip> = ${JSON.stringify(strips, null, 2)};

/** Aspect of one tile, so the band can be sized from its height alone. */
export const FLAG_STRIP_HEIGHT = ${FLAG_H};
`;

writeFileSync(resolve(ROOT, "lib/flags.ts"), file);
const kb = (file.length / 1024).toFixed(1);
console.log(
  `lib/flags.ts — ${Object.keys(strips).length} strips, ${Object.values(BY_LOCALE).flat().length} flags, ${kb} kB`,
);
