#!/usr/bin/env node
/**
 * Writes `lib/flags.ts` with only the flags the locale flourish uses.
 *
 * Same reasoning as `generate-tech-icons.mjs`: `country-flag-icons` ships every
 * country on earth, so the ones we want are extracted at build time and the
 * package stays a devDependency with no runtime presence.
 *
 * The source SVGs contain no `id`, `mask` or `clipPath`, which is what makes it
 * safe to inline the same markup many times in one document.
 *
 * Usage: node scripts/generate-flags.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Countries per language.
 *
 * Not "every country where the language is spoken" — that list runs past fifty
 * and says nothing. These are the ones a reader recognises at a glance, capped
 * at eight so the strip stays a flourish rather than an atlas.
 */
const BY_LOCALE = {
  // The CPLP, minus the members whose flags are unreadable at this size.
  pt: ["PT", "BR", "AO", "MZ", "CV", "GW", "ST", "TL"],
  en: ["GB", "US", "CA", "IE", "AU", "NZ", "ZA", "IN"],
  es: ["ES", "MX", "AR", "CO", "CL", "PE", "UY", "CU"],
};

const inner = (svg) => svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");

const codes = [...new Set(Object.values(BY_LOCALE).flat())].sort();
const bodies = Object.fromEntries(
  codes.map((code) => [
    code,
    inner(readFileSync(resolve(ROOT, `node_modules/country-flag-icons/3x2/${code}.svg`), "utf8")),
  ]),
);

const file = `// Generated by scripts/generate-flags.mjs — do not edit by hand.
// Source: country-flag-icons (3x2), which carries no ids, so the same markup
// can be inlined repeatedly without collisions.

import type { Locale } from "@/lib/i18n/types";

/** Inner markup for a "0 0 513 342" viewBox, keyed by ISO 3166-1 alpha-2. */
export const flagBodies: Record<string, string> = ${JSON.stringify(bodies, null, 2)};

/** Which flags drift past when a language is chosen. */
export const flagsByLocale: Record<Locale, readonly string[]> = ${JSON.stringify(BY_LOCALE, null, 2)};
`;

writeFileSync(resolve(ROOT, "lib/flags.ts"), file);
console.log(`lib/flags.ts — ${codes.length} flags, ${(file.length / 1024).toFixed(1)} kB`);
